### ISSUE TITLE
Adding support for getting lyrics for a local MP3 file

### ISSUE THREAD

**Issue by mukul-mehta** [SwagLyrics/SwagLyrics#11]
I believe since a lot of us have mp3's locally on our machines, it would be a good idea to extend the app.

Ex: We can use `swaglyrics -c --file example_song.mp3`

https://github.com/adrienjoly/mp3-fetch-metadata fetches metadata and then we pass the song and artist name as parameters to our existing application.

**Comment by GermaVinsmoke** [comment]
This is similar to searching for lyrics using `--song` and `--artist`
Like in case of `--file` we got to give the complete path of that file which I don't think anyone would like to give, so if a person knows the song and artist name so he can directly search for the lyrics.

**Comment by aadibajpai** [comment]
^Agreed, the relevant PR for --song --artist will address both issues.

**Comment by mukul-mehta** [comment]
Yes. Even I'm fully sure of the idea but I was thinking of it for cases you might not have the artist name for. It shouldn't be very important to implement this.

**Comment by aadibajpai** [comment]
So I realise you could load your music into Spotify and then use SwagLyrics ¯\(ツ)/¯
