### ISSUE TITLE
Add support for getting lyrics for a specified song

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics#5]
Eg. If I want to get the lyrics of whatever song instead of the currently playing one, I should be able to. 

Something like `swaglyrics -c --song Derezzed --artist Daft Punk`

**Comment by sprakriti** [comment]
Hi! I'd like to take up this issue.

**Comment by aadibajpai** [comment]
@sprakriti no one's stopping you :)

**Comment by mukul-mehta** [comment]
This is to be done for both -c and -t arguments (along with the song and artist name), right?

**Comment by aadibajpai** [comment]
@mukul-kgp yes

**Comment by aadibajpai** [comment]
Actually I don't think this is the direction we want to go
