### ISSUE TITLE
[BUG]  Application needs to be started before getting songs from Spotify (Chrome Extension) 

### ISSUE THREAD

**Issue by TarunKurella** [SwagLyrics/SwagLyrics#7]
application needs to be started before getting songs from Spotify ( extension) due to one-way communication.

 I believe it can be solved using web Sockets.

**Comment by aadibajpai** [comment]
I think on startup with the --chrome flag, the application could query the extension to fetch the song. Henceforth, the extension will post the song when it changes but initially it could be done by the application.

**Comment by TarunKurella** [comment]
yes, but instead of having muttiple api's having 2 way comunication,
usage of websocket would be much more efficient

**Comment by aadibajpai** [comment]
Sure, if it's better and a more efficient solution.

**Comment by aadibajpai** [comment]
Why can't one GET request be sent to the extension locally initially instead of adding websockets?

**Comment by TarunKurella** [comment]
Yes, it can be done. Buts adds unnecessary boilerplate on the extension side for that single request

**Comment by GermaVinsmoke** [comment]
Came across this - https://github.com/phandd/spotless @aadibajpai

**Comment by aadibajpai** [comment]
> 
> 
> Came across this - https://github.com/phandd/spotless @aadibajpai

I just want to get this one working haha

**Comment by anantha1999** [comment]
@aadibajpai Could you please elaborate on this problem?

**Comment by anantha1999** [comment]
Could someone please elaborate on this problem?

**Comment by aadibajpai** [comment]
> Could someone please elaborate on this problem?

I don't think this one is relevant anymore
