### ISSUE TITLE
Unsupported.txt gets created in the directory from which SwagLyrics is run instead of the package installation directory

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics#8]
There is an unsupported.txt that gets copied over to the site-packages directory where SwagLyrics' files are when you pip install it.

But on execution, the unsupported.txt gets created from where `swaglyrics` is run and gets updated from the server instead of the one in the site-packages directory.

Should be easy to fix.

**Comment by mukul-mehta** [comment]
To update the unsupported.txt in the installation directory, you'd need to give sudo access right?

**Comment by aadibajpai** [comment]
> To update the unsupported.txt in the installation directory, you'd need to give sudo access right?

I'm not sure, I'm on Windows myself.

**Comment by mukul-mehta** [comment]
On Ubuntu, it's needed. Do you think it's a good idea to ask users for the sudo password every time they want to run the app?

One possible solution might be placing unsupported.txt in another folder which doesn't require root privileges.

**Comment by aadibajpai** [comment]
@mukul-mehta in that case yes, the next best solution would be to place it somewhere else

**Comment by aadibajpai** [comment]
should be fixed in latest commit

**Comment by aadibajpai** [comment]
Fixed v0.2.8
