### ISSUE TITLE
Sync lyrics to song

### ISSUE THREAD

**Issue by aadibajpai** [SwagLyrics/SwagLyrics#9]
Similar to how Musixmatch and other similar applications do it but programmatically and not manually.

Would require research and may not be easy.

**Comment by mukul-mehta** [comment]
Hi!

I'd like to start reading about possible solutions and work on this issue!

**Comment by aadibajpai** [comment]
No one's stopping you 🙂

**Comment by GermaVinsmoke** [comment]
Possible solution to this is to generate LRC file - https://en.m.wikipedia.org/wiki/LRC_(file_format)

**Comment by GermaVinsmoke** [comment]
Musixmatch is using ACRCloud to detect the audio, not only Musixmatch but Alibaba, Xiaomi, and many more are also using that.

**Comment by aadibajpai** [comment]
@GermaVinsmoke detecting the song from audio?

**Comment by GermaVinsmoke** [comment]
Yeah, calling it as audio fingerprint. You'll find "How Shazam works" .

**Comment by aadibajpai** [comment]
Yeah I know, I think some project in CCX used deja vu to do that. What's the point though? We get the song from Spotify anyway.

**Comment by GermaVinsmoke** [comment]
Point is - we're getting the song from Spotify and after that we're scraping the lyrics from genius, we will also try the performance with Google but we're only getting full lyrics. The problem is how to get the LRC of that song 🤔

**Comment by GermaVinsmoke** [comment]
There's this app [Quick lyrics] (https://github.com/QuickLyric/QuickLyric) which uses ACRCloud to detect the song and then it uses Lyricsfind to get the synchronised lyrics. The lyrics that Google is showing is through Lyricsfind only.

**Comment by aadibajpai** [comment]
@GermaVinsmoke I see, this makes sense. LyricFind is closed-source unfortunately.

**Comment by GermaVinsmoke** [comment]
Yeah, that's the main problem, Lyricsfind is closed source, we need to find a way to sync lyrics, somehow to generate LRC file.

**Comment by aadibajpai** [comment]
@GermaVinsmoke can you see where in QuickLyric they hook up LyricFind?

**Comment by GermaVinsmoke** [comment]
Sure but that'll take some time, I was also reading some research papers on how they generate SRT files.

On one site, SRT files are available [RentAnAdviser](https://www.rentanadviser.com/en/subtitles/subtitles4songs.aspx) but then only 14k songs are available on it and it's not easy to scrap that, no proper format of url 😐

**Comment by mukul-mehta** [comment]
There's a website called https://syair.info that has LRC files for quite a number of files. It would be difficult to scrape it though since there's no fixed format for a URL

**Comment by aadibajpai** [comment]
closing since https://swaglyrics.dev/autosynch
